# Generated by cpp11: do not edit by hand

dunisph_impl <- function(x, log) {
  .Call(`_sphericaldistributions_dunisph_impl`, x, log)
}

punisph_impl <- function(x) {
  .Call(`_sphericaldistributions_punisph_impl`, x)
}

runisph_impl <- function(n) {
  .Call(`_sphericaldistributions_runisph_impl`, n)
}

dvmf_impl <- function(x, mu, kappa, log) {
  .Call(`_sphericaldistributions_dvmf_impl`, x, mu, kappa, log)
}

pvmf_impl <- function(x, mu, kappa) {
  .Call(`_sphericaldistributions_pvmf_impl`, x, mu, kappa)
}

rvmf_impl <- function(n, mu, kappa) {
  .Call(`_sphericaldistributions_rvmf_impl`, n, mu, kappa)
}

fit_vmf_impl <- function(x) {
  .Call(`_sphericaldistributions_fit_vmf_impl`, x)
}

dwatson_impl <- function(x, mu, kappa, log) {
  .Call(`_sphericaldistributions_dwatson_impl`, x, mu, kappa, log)
}

pwatson_impl <- function(x, mu, kappa) {
  .Call(`_sphericaldistributions_pwatson_impl`, x, mu, kappa)
}

rwatson_impl <- function(n, mu, kappa) {
  .Call(`_sphericaldistributions_rwatson_impl`, n, mu, kappa)
}

fit_watson_impl <- function(x) {
  .Call(`_sphericaldistributions_fit_watson_impl`, x)
}
