# Generated by cpp11: do not edit by hand

dvmf_impl <- function(x, mu, kappa, log) {
  .Call(`_sphericaldistributions_dvmf_impl`, x, mu, kappa, log)
}

pvmf_impl <- function(x, mu, kappa) {
  .Call(`_sphericaldistributions_pvmf_impl`, x, mu, kappa)
}

rvmf_impl <- function(n, mu, kappa) {
  .Call(`_sphericaldistributions_rvmf_impl`, n, mu, kappa)
}

mean_vmf_impl <- function(x) {
  .Call(`_sphericaldistributions_mean_vmf_impl`, x)
}

dwatson_impl <- function(x, mu, kappa, log) {
  .Call(`_sphericaldistributions_dwatson_impl`, x, mu, kappa, log)
}

pwatson_impl <- function(x, mu, kappa) {
  .Call(`_sphericaldistributions_pwatson_impl`, x, mu, kappa)
}

rwatson_impl <- function(n, mu, kappa) {
  .Call(`_sphericaldistributions_rwatson_impl`, n, mu, kappa)
}

mean_watson_impl <- function(x) {
  .Call(`_sphericaldistributions_mean_watson_impl`, x)
}
