# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The Watson distribution
#'
#' @param x A numeric matrix of shape \eqn{n \times 3} where \eqn{n} is the
#'   number of samples and the columns represent the x, y, z coordinates
#'   of the samples.
#' @param mu A numeric matrix of shape \eqn{1 \times 3} representing the mean
#'   axis of the Watson distribution.
#' @param kappa A positive numeric value representing the concentration
#'   parameter of the Watson distribution.
#' @param log A logical value indicating whether the log density should be
#'   returned. Defaults to `false`.
#' @param n An integer value indicating the number of samples to generate.
#'
#' @return
#' - `dwatson` returns a numeric vector of length \eqn{n} containing the
#' density values of the Watson distribution.
#' - `pwatson` returns a numeric vector of length \eqn{n} containing the
#' cumulative density values of the Watson distribution.
#' - `qwatson` returns a numeric matrix of shape \eqn{n \times 3} containing
#' the quantile values of the Watson distribution.
#' - `rwatson` returns a numeric matrix of shape \eqn{n \times 3} containing
#' the random samples from the Watson distribution.
#'
#' @examples
#' mu <- c(1, 0, 0)
#' kappa <- 10
#' n <- 100
#' spl <- rwatson(n, mu, kappa)
#' dwatson(spl, mu, kappa)
#' pwatson(spl, mu, kappa)
#'
#' @name watson
NULL

#' @export
#' @rdname watson
dwatson <- function(x, mu, kappa, log = FALSE) {
    .Call(`_sphericaldistributions_dwatson`, x, mu, kappa, log)
}

#' @export
#' @rdname watson
pwatson <- function(x, mu, kappa) {
    .Call(`_sphericaldistributions_pwatson`, x, mu, kappa)
}

#' @export
#' @rdname watson
rwatson <- function(n, mu, kappa) {
    .Call(`_sphericaldistributions_rwatson`, n, mu, kappa)
}

mean_watson_impl <- function(x) {
    .Call(`_sphericaldistributions_mean_watson_impl`, x)
}

